dist: trusty
sudo: false

# Get deps
before_script:
- npm install

# Build and clean
script:
  - rollup -c
  - node_modules/gulp/bin/gulp.js --gulpfile gulpfile.babel.js build
  
# Deploy
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_BUCKET
  skip_cleanup: true
  local_dir: dist  
  acl: public_read