baseURL = "/"
languageCode = "en-us"
title = "Hugo Boilerplate"
publishDir = "dist"
enableRobotsTXT = true

[[menu.global]]
    name = "Page 1"
    identifier = "page-1"
    url = "/page-1"

[[menu.global]]
    name = "Page 2"
    identifier = "page-2"
    url = "/page-2"

[[menu.global]]
    name = "Page 3"
    identifier = "page-3"
    url = "/page-3"

[[menu.global]]
    name = "Page 4"
    identifier = "page-4"
    url = "/page-4"   

[[menu.global]]
    name = "Posts"
    identifier = "posts"
    url = "/posts"

[[menu.footer]]
    name = "Page 1"
    identifier = "page-1"
    url = "/page-1"

[[menu.footer]]
    name = "Page 2"
    identifier = "page-2"
    url = "/page-2"

[[menu.footer]]
    name = "Page 3"
    identifier = "page-3"
    url = "/page-3"

[[menu.footer]]
    name = "Page 4"
    identifier = "page-4"
    url = "/page-4"        

[[menu.footer]]
    name = "Posts"
    identifier = "posts"
    url = "/posts"

[params]
    google_analytics_id = "test"
    theme_color = "#ff6600"
    tile_color = "#ff6600"
    favicon = "/_img/favicon.jpg"