baseURL = "/"
enableRobotsTXT = true
languageCode = "en-us"
publishDir = "dist"
title = "Hugo Boilerplate"
[[menu.footer]]
identifier = "github"
name = "Github"
url = "https://github.com/nateluzod/hugo-boilerplate"
weight = 6
[[menu.footer]]
identifier = "posts"
name = "Posts"
url = "/posts"
weight = 5
[[menu.footer]]
identifier = "page-4"
name = "Page 4"
url = "/page-4"
weight = 4
[[menu.footer]]
identifier = "page-3"
name = "Page 3"
url = "/page-3"
weight = 3
[[menu.footer]]
identifier = "page-2"
name = "Page 2"
url = "/page-2"
weight = 2
[[menu.footer]]
identifier = "page-1"
name = "Page 1"
url = "/page-1"
weight = 1
[[menu.global]]
identifier = "posts"
name = "Posts"
url = "/posts"
weight = 1
[[menu.global]]
identifier = "page-4"
name = "Page 4"
url = "/page-4"
weight = 2
[[menu.global]]
identifier = "page-3"
name = "Page 3"
url = "/page-3"
weight = 3
[[menu.global]]
identifier = "page-2"
name = "Page 2"
url = "/page-2"
weight = 4
[[menu.global]]
identifier = "page-1"
name = "Page 1"
url = "/page-1"
weight = 5
[params]
favicon = "/_img/favicon.jpg"
google_analytics_id = "test"
theme_color = "#ff6600"
tile_color = "#ff6600"
